### PR TITLE
Major upgrade of gem to use the latest Ruby, Faraday, Activesupport, and Sinatra

### PR DESCRIPTION
**Pull request by TRex22**
# What does this PR do?

- Upgrade Ruby to Version 3.3.5
- Upgrade Faraday to Version 2
- Removes faraday_middleware as it is no longer supported
- Updates the Connection builder to not use the calls specific to faraday_middleware
- Upgrade activesupport to 7.2
- Upgrade Sinatra to version 3
- Update change log

### CODE REVIEW

**Comment by andyw8** [comment]
Thanks for this. I no longer use Pocket, but I'm happy to merge this once it passes. I'm noticing a CI failure relating to `standard`. If you run `bundle exec rake` you should see it.

**Comment by TRex22** [comment]
@andyw8 Ive made the suggested changes

**Comment by andyw8** [comment]
Looks like the changelog checker action job isn't working but I'll merge anyway.

**Comment by andyw8** [comment]
https://rubygems.org/gems/pocket-ruby/versions/0.6.0

**Comment by TRex22** [comment]
Thank you 🙏🏻

**Pull request merged**
